### ISSUE TITLE
v1.3.40 - Compare Output - selected database

### ISSUE THREAD

**Issue by NathanaelThompson** [sethreno/schemazen#111]
When comparing source database A and target database B, the output is written as a script for database B. However, the output script assumes the user is already using database B. The fix, at a guess, would be to add a small query to the beginning of the database explicitly stating to use the target database.

```
USE TARGET_DATABASE
GO
```

**Comment by sethreno** [comment]
This is intentional. All scripts generated by schemazen must explicitly be run against a database. I think it wold be dangerous for the script to include this USE statement in cases where the user explicitly ran it against a different database.
