### ISSUE TITLE
Make Data Export Optional

### ISSUE THREAD

**Issue by frankvandenbergh** [sethreno/schemazen#112]
Thanks for this component.

I used this to generate scripts of my SQL Server 2014 database. Next I used this to create a database in a VM Ware SQL Server 2008R2. All this trouble to create a bak file I can share...

I suppressed the ExportData(tableHint, log); command (in Database.cs). So this component didn't export the data, but only the database structure. Next I copied data via sp_addlinkedserver and "INSERT INTO [VMServer].[{0}].[dbo].{1} SELECT * from {1};" commands.

Is it possible to add an argument in order not to export data?

**Comment by sethreno** [comment]
Data export is optional. Just don't specify any of the following options when running the script command:

* dataTables
* dataTablesPattern
* tablesHint
