### ISSUE TITLE
Foreign Keys Generating Outside of Create Table Statement

### ISSUE THREAD

**Issue by AmyEslinger** [sethreno/schemazen#14]
Why are the foreign keys being scripted into their own folder when the primary keys, defaults and indexes are included in the create table statement?  I’d prefer it all in one file.  Plus the file names are the same and that’s really confusing.

**Comment by sethreno** [comment]
The data import feature has been revived so adding this option is more complicated now. Also, no one else has shown interest. Closing as wont fix.
