### ISSUE TITLE
Not getting data dump?

### ISSUE THREAD

**Issue by franksiler** [sethreno/schemazen#160]
I pulled the latest release and have successfully pulled some very nice schema files from SQL 2012 Enterprise and SQL 2017 Express.  However, none of the data exports.  I can successfully export tables by naming them with the `--dataTables=` option; I tried using `*` as a regex but that fails.  Can you please clarify how I would dump all the data, ideally as scripts that can simply be run to reimport the data, or with a load script alongside the TSV/CSV?  Thanks!

Frank

**Comment by sethreno** [comment]
Try ".*"

In regex . is the wildcard and * means match the preceding expression zero
or more times.

**Comment by franksiler** [comment]
Worked a treat, thanks!
