### ISSUE TITLE
Add support for synonyms.

### ISSUE THREAD

**Issue by AmyEslinger** [sethreno/schemazen#17]
I didn’t get a Synonym or User folder, those would be nice for a complete database generation.

**Comment by keith-hall** [comment]
some information on synonyms here https://msdn.microsoft.com/en-us/library/ms177544.aspx and http://stackoverflow.com/questions/1246006/what-is-the-use-of-synonym-in-sql-server-2008
The following article shiws that you can get metadata from sysobjects http://www.mssqltips.com/sqlservertip/1576/benefits-and-limitations-of-using-synonyms-in-sql-server-2005/

**Comment by coenier** [comment]
This will be nice if added
