### ISSUE TITLE
Logging level quiet

### ISSUE THREAD

**Issue by aboy021** [sethreno/schemazen#182]
Please add the ability to specify a Quiet or Silent logging level.

I'm using SchemaZen in an integration test harness to create a sandbox database. The Console.WriteLine calls in SchemaZen end up overwhelming the output from my integration tests. Being able to specify a quieter logging level would really help this. I'm already specifying Verbose = false. 

Something like [NLog](https://nlog-project.org/) for the logging would be nice, but I realize that it's a bit of a big hammer.

By the way, this library is totally awesome and has made some of my difficult problems simply disappear.

**Comment by sethreno** [comment]
@aboy021 Thanks for reporting. I'm porting this to net6 and have updated the tests to use more modern logging. I should get around to doing the same for the the the Console & Model.

Maybe piping to a file would work in the meantime?

    schemaZen create > some_file.txt

**Comment by aboy021** [comment]
Thank you!

This was more of an issue when I was calling schemaZen as a library. I've moved to command line usage and it's not a big deal.

**Comment by aboy021** [comment]
When I was calling SchemaZen as a library I was able to suppress the Console.WriteLine calls using this:

```cs
Console.SetOut(StreamWriter.Null);
```

Not ideal, but it was an acceptable hack at the time.

**Comment by aboy021** [comment]
This is resolved in recent releases since the ILogger support was added.
