### ISSUE TITLE
Linux Version

### ISSUE THREAD

**Issue by lixaotec** [sethreno/schemazen#186]
Does it works in Linux?

Would be nice to have a linux version (without hacking like using Wine)

**Comment by sethreno** [comment]
Not at the moment. I've started porting it to dotnet core in a local
branch. Once that's done I'll run on platforms other than Windows.

I don't have a lot of free time to work on it at the moment though. It
might be six months or more before it's released.

**Comment by lixaotec** [comment]
Would you share this branch, i could try helping to port

**Comment by rhumborl** [comment]
@lixaotec I have created a PR for a ,net 5 port, including publish profiles for linux arm and x64. Would be great if you could test the linux versions.

https://github.com/sethreno/schemazen/pull/194
