### ISSUE TITLE
I forked this repo and added some additional features (with breaking changes)

### ISSUE THREAD

**Issue by idan-h** [sethreno/schemazen#198]
Hey, I forked this repo and added some additional features that breaks the current one. It creates a single script instead of a directory, and in the future it will have PS scripts to support integration with SSDT.  
  
https://github.com/idan-h/schemazenPlus

If you would like to integrate those features to here instead I will gladly do so, but I felt they are too breaking and too specific for this repo.

**Comment by sethreno** [comment]
Thanks for letting me know.
