### ISSUE TITLE
Reverse Code First

### ISSUE THREAD

**Issue by fasteddys** [sethreno/schemazen#201]
Hello, do you have an option likr Emmet or ZenCoding to  create schemas quickly

**Comment by sethreno** [comment]
I don't understand the question. Can you provide more detail? Are you requesting a new feature for schemazen?

**Comment by fasteddys** [comment]
sure, let me explain.

I would like to create the models and schemas, but it would nice to have a short support like [Emmet Coding ](https://emmet.io/) or ZenCoding
