### ISSUE TITLE
Error scripting column geometry. SQL data type geometry is not supported.

### ISSUE THREAD

**Issue by GordonData** [sethreno/schemazen#211]
Error scripting column geometry. SQL data type geometry is not supported.

**Comment by keith-hall** [comment]
Each datatype needs specific handling to ensure it scripts the column correctly. `geometry` needs to be added to the list in https://github.com/sethreno/schemazen/blob/bacee1a768df0991995518954c10bd3250ffdef8/Library/Models/Column.cs#L135.
