### ISSUE TITLE
Add support for user-defined table types

### ISSUE THREAD

**Issue by mwittmann** [sethreno/schemazen#23]
SchemaZen does not script User-defined table types (UDTTs).

User-defined table types (UDTTs) are defined just like tables, so the SchemaZen Table class could be extended to capture UDTTs.  However, the metadata is not available from INFORMATION_SCHEMA.  

The following query lists user-defined table types:

```SQL
SELECT *
  FROM sys.table_types
  WHERE is_user_defined = 1
```

The following query can be used to get all of the UDTT columns:

```SQL
SELECT 
	s.name as schema_name,
	tt.name as table_type_name, 
	c.*
FROM sys.columns c
INNER JOIN sys.table_types tt on tt.type_table_object_id = c.object_id
INNER JOIN sys.schemas s on tt.schema_id = s.schema_id 
WHERE tt.is_user_defined = 1
ORDER BY schema_name, table_type_name, column_id
```

**Comment by sethreno** [comment]
This is fixed in version 1.3.1
