### ISSUE TITLE
Bug in command-line paramters DataTablePatterns

### ISSUE THREAD

**Issue by foodanger** [sethreno/schemazen#27]
Hi, 
I have just debugged your code because of a bug in DataTablePatterns. (->The assembly doesn't respond to DataTablePattern option).
I found the failing code in class Script, Method Script() and wrote the following patch (You used two times DataTables instead once DataTablePattern)

Thanks for your work, it helps me a lot
Roland

PATCH:
===================
		public Script() : base(
			"Script", "Generate scripts for the specified database.") {
			HasOption(
				"dataTables=",
				"A comma separated list of tables to export data from.",
				o => DataTables = o);
			HasOption(
				"dataTablesPattern=",
				"A regular expression pattern that matches tables to export data from.",
				o => DataTablesPattern = o); //HERE !!!! --->
		}

**Comment by sethreno** [comment]
This is fixed in 1.1.7. Thanks for reporting.
