### ISSUE TITLE
Error in exported foreign keys pointing to compound primary keys

### ISSUE THREAD

**Issue by pozibrothers** [sethreno/schemazen#28]
Hi.

The database I'm trying to script has several compound primary keys like this:

```SQL
CONSTRAINT [PK_NAME] PRIMARY KEY CLUSTERED ([c_column], [a_column], [b_column])
```

The application generates then properly in the table creation script. The problem shows if there is a foreign key pointing to that primary key.

The code the application generates is the following:

```SQL
ALTER TABLE [dbo].[FK_TABLE] WITH CHECK ADD CONSTRAINT [FK_TABLE_TO_PK_TABLE]
   FOREIGN KEY([a_column], [b_column], [c_column]) REFERENCES [dbo].[PK_TABLE] ([a_column], [b_column], [c_column])
   ON UPDATE NO ACTION
   ON DELETE NO ACTION
```

It changes the column order, causing an error when creating the database from the exported model. The PK is defined [c, a, b], but the FK is sorted [a, b, c]. It happens in all cases with compound PK's.

Regards.

**Comment by sethreno** [comment]
Thanks for reporting. This is the next thing I'll fix.
