### ISSUE TITLE
Output progress to console or file

### ISSUE THREAD

**Issue by erandros** [sethreno/schemazen#30]
Maybe log after each action is done.
Maybe accept verbose or silent as options.
If I get some time, I'll clone and do a PR.

**Comment by keith-hall** [comment]
I think that logging progress to the console should be enough, as console output can be redirected to a file if desired

**Comment by sethreno** [comment]
This is fixed in 1.3.3. Use `--verbose true` to output and ` ... > somefile.txt` to write to file.
