### ISSUE TITLE
Missing Stored procedures

### ISSUE THREAD

**Issue by coenier** [sethreno/schemazen#33]
When the following message is encountered 
Warning: SQL_STORED_PROCEDURE dbo.SOMEPROCNAME has been renamed since it's definition.

It reports "Snapshot successfully created at" but when the stored procedure folder is viewed none of the other stored procedures are scripted.

The problem is fixed when a alter statement is run on the stored proc

**Comment by keith-hall** [comment]
Hi Coenie,

I believe that I have fixed this since the latest release (in commit 21046be0b26f504146fa4b6fb185ff44c1d85ca3 I think) - hopefully the next release will include this fix...

Thanks

**Comment by coenier** [comment]
Ok cool

**Comment by sethreno** [comment]
I'll include this in the next release. Hopefully this weekend.
