### ISSUE TITLE
Error - unable to cast object of type 'System.DBNull' to type 'System.String' when scripting database

### ISSUE THREAD

**Issue by db75** [sethreno/schemazen#36]
Hi, on a server:
Microsoft SQL Server 2008 R2 (SP3) - 10.50.6000.34 (X64)
    Aug 19 2014 12:21:34
    Copyright (c) Microsoft Corporation
    Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)

using the command on 
schemazen.exe script -s="SERVERNAME" -b="DATABASENAME" -u="USERNAME" -p=
"PASSWORD" -d="LOCALFOLDER" -o=Y

I receive an error:
Unable to cast object of type 'System.DBNull' to type 'System.String'.
   at SchemaZen.model.Database.LoadConstraintsAndIndexes(SqlCommand cm)
   at SchemaZen.model.Database.Load()
   at SchemaZen.console.Script.Run(String[] args)
   at ManyConsole.ConsoleCommandDispatcher.DispatchCommand(IEnumerable`1 commands, String[] arguments, TextWriter consoleOut, Boolean skipExeInExpectedUsage)
   at SchemaZen.console.Program.Main(String[] args)

**Comment by keith-hall** [comment]
Please can you run the following sql on this database, and let us know in which column(s) the null occurs:
```sql
select 
	s.name as schemaName,
	t.name as tableName, 
	t.baseType,
	i.name as indexName, 
	c.name as columnName,
	i.is_primary_key, 
	i.is_unique_constraint,
	i.is_unique, 
	i.type_desc,
	isnull(ic.is_included_column, 0) as is_included_column
from (
	select object_id, name, schema_id, 'T' as baseType
	from   sys.tables
	union
	select object_id, name, schema_id, 'V' as baseType
	from   sys.views
	) t
	inner join sys.indexes i on i.object_id = t.object_id
	inner join sys.index_columns ic on ic.object_id = t.object_id
		and ic.index_id = i.index_id
	inner join sys.columns c on c.object_id = t.object_id
		and c.column_id = ic.column_id
	inner join sys.schemas s on s.schema_id = t.schema_id
order by s.name, t.name, i.name, ic.key_ordinal, ic.index_column_id
```

**Comment by db75** [comment]
Results attached file
the rest can be sent by mail



![2015-10-09_145845](https://cloud.githubusercontent.com/assets/11922849/10393327/aea31aba-6e97-11e5-8f59-c06ad8cf30d0.jpg)

**Comment by keith-hall** [comment]
It does seem to correctly include the IX_PART index in the results (row 8) - to my eyes, it appears that it just contains an additional (undesired) record with a type_desc of HEAP and indexName that is null.
Seeing as a heap is a table without a clustered index, and therefore is implicit - and isn't something that can be scripted - I believe the fix for this will be to filter out HEAP records when SchemaZen loads indexes.

**Comment by db75** [comment]
please let your email - there are other errors
