### ISSUE TITLE
When generating a script for the object of stored procedure or function, one extra empty line is added to the end of definition.

### ISSUE THREAD

**Issue by AlexeyKasjanov** [sethreno/schemazen#43]
If a single script for a stored procedure or function, obtained by SchemaZen, perform on the database by the utility sqlcmd -i (after removing the existing object from the database), and then again get it via SchemaZen, the new version of the script will be different from the old version one  empty line, although no manual modifications to the script file was not fulfilled. 
It seems the new line is added to the definition of the object after it is created from a script by sqlcmd -i. Because the line with the following GO written to the definition as a carriage return.

**Comment by AlexeyKasjanov** [comment]
Excuse me. It seems that this is not the fault of the program schemZen. The new line is added to the definition of the object after it is created from a script by sqlcmd -i.

**Comment by rmarskell** [comment]
I've also noticed similar issues with extra new lines being add to the beginning and end of scripts. Perhaps you could parse it to remove all newlines between the "GO" & the first proc line, and the last proc statement & the following "GO" statement.

**Comment by sethreno** [comment]
This is fixed in https://github.com/sethreno/schemazen/releases/tag/1.3.51
