### ISSUE TITLE
Making it work on Azure

### ISSUE THREAD

**Issue by vincent** [sethreno/schemazen#45]
Hi, thanks for SchemaZen, saved me many hours of headaches :)

Just so you know, it does not work directly on Azure SQL, because `sys.server_principals` does not exist.

I just commented out `LoadUsersAndLogins`, that I did not need anyway, and it worked perfectly it seems.

**Comment by keith-hall** [comment]
Thanks for reporting, I have now made a fix and added it to my [pull request](https://github.com/sethreno/schemazen/pull/42). :)
