### ISSUE TITLE
Check object existence in scripts

### ISSUE THREAD

**Issue by chris-lu** [sethreno/schemazen#46]
Hi !

Fortunately, I found your great project. Thanks for your work.
I think a feature that would be nice would be to have an option checking object existence in creation scripts (like the MSSMS option having the same name), adding "IF NOT EXISTS" instruction on the different scripts before trying to recreate them.

That's just a suggestion :)

**Comment by keith-hall** [comment]
Hi, thanks for the feedback and suggestion.  Personally, I don't want this option in SchemaZen, and I will explain why.  The scripts that are created by SchemaZen are designed to be executed by SchemaZen when using the `create` command.  This command creates a new database, and executes the scripts against that.  So in this case, we know that none of the objects will already exist, and therefore it seems that to check would be a waste of time, and potentially lead to some confusion.

My understanding therefore is that you would like to execute the scripts manually on an existing database, such that this option would have some use for you. But what about the situation where an object exists but differs?  Simply using an `IF NOT EXISTS` instruction won't find such cases.  This is where SchemaZen's `compare` command comes in handy, and would, in my opinion, be more reliable/accurate for ensuring that two database schemas match.

I realize that in some cases, you may only want certain objects from one database to be copied to another, and then the technique that I just described doesn't really match the use-case.  But perhaps it would be better to get the comparison functionality altered to only look at specific objects?

What do you think? Feel free to disagree with me, maybe I am missing something... ;)

**Comment by sethreno** [comment]
Thanks for the support @chris-lu. I'm glad you found schemazen useful.

I agree with @keith-hall on this. I'm going to close this issue, but if we misunderstood something or you'd like to discuss it further please reply or bring it up on gitter.
