### ISSUE TITLE
Compare database with schema scripts directory 

### ISSUE THREAD

**Issue by MisterY** [sethreno/schemazen#47]
Would it be possible, besides comparing two databases, to compare a database to the schema scripts directory directly?
The benefits are that the schema changes can be propagated via source control and compared to databases at different servers. The comparison to scritps directory avoids having to generate the database from scripts and then compare the two databases.

**Comment by sethreno** [comment]
Yes, this is possible, but requires a bit of work. There's an existing feature request for this (see #26). I'm going to close this issue because it's a duplicate, but feel free to comment on #26. Thanks.
