### ISSUE TITLE
"Specified cast is not valid" during script phase

### ISSUE THREAD

**Issue by ChrisMDaly** [sethreno/schemazen#55]
I have not been able to use any releases after  1.19 as starting with 1.2.0 i get an error "Specified cast is not valid".   I was wondering if this is a known issue, or if you had some tips that I could use to see what you do not like in our database?

SchemaZen119 script -s 127.0.0.1 -b TestDB -d TestDB -u admin -p xx
Snapshot successfully created at TestDB

SchemaZen120 script -s 127.0.0.1  -b TestDB -d TestDB -u admin -p xx
Specified cast is not valid.
   at SchemaZen.model.Database.LoadColumnsBase(IDataReader dr, List`1 tables)
   at SchemaZen.model.Database.LoadColumns(SqlCommand cm)
   at SchemaZen.model.Database.Load()
   at SchemaZen.console.Script.Run(String[] args)
   at ManyConsole.ConsoleCommandDispatcher.DispatchCommand(IEnumerable`1 command
s, String[] arguments, TextWriter consoleOut, Boolean skipExeInExpectedUsage)
   at SchemaZen.console.Program.Main(String[] args)

**Comment by ChrisMDaly** [comment]
I managed to find where the issue was in code and get around it but i still don't understand why it was happening.   c.Scale = (int) dr["NUMERIC_SCALE"]; was causing the error, and     c.Scale = Int32.Parse (dr["NUMERIC_SCALE"].ToString ());  works.

I would love to hear some of the experts opinions on this as i don't see a difference in the original cast and the parse.

The value in  dr["NUMERIC_SCALE"] was 2,

Original Code:
	switch (c.Type) {
					case "binary":
					case "char":
					case "nchar":
					case "nvarchar":
					case "varbinary":
					case "varchar":
						c.Length = (int) dr["CHARACTER_MAXIMUM_LENGTH"];
						break;
					case "decimal":
					case "numeric":
						c.Precision = (byte) dr["NUMERIC_PRECISION"];
						c.Scale = (int) dr["NUMERIC_SCALE"];
						break;
				}

Changed Code:
			switch (c.Type) {
					case "binary":
					case "char":
					case "nchar":
					case "nvarchar":
					case "varbinary":
					case "varchar":
						c.Length = (int) dr["CHARACTER_MAXIMUM_LENGTH"];
						break;
					case "decimal":
					case "numeric":
						c.Precision = (byte) dr["NUMERIC_PRECISION"];
					//	c.Scale = (int) dr["NUMERIC_SCALE"];
                        c.Scale = Int32.Parse (dr["NUMERIC_SCALE"].ToString ());
						break;
				}

Thanks!

**Comment by keith-hall** [comment]
Hi, thanks for reporting.  It looks like the query that gets column information for table types gets the "scale" as a sql `tinyint` (C# `byte`) type, but the query that gets the column information for normal tables gets the "scale" as a sql `int` type, and for some reason it fails when it tries to cast the former to a C# `int`.

I will add a test case and a fix.
