### ISSUE TITLE
Table_Types scripted, but not created.   Is this still under development?

### ISSUE THREAD

**Issue by ChrisMDaly** [sethreno/schemazen#57]
Hello All,

Thanks for such fast turn around on issues.   This is a great tool!

Question on the UDT's that you added a couple releases back.   I see that they are scripted, but when i create a database, the directory "Table_Types" is not loaded.   Is this still under development from a create stand point??

Code (no table_types):
		private static readonly string[] dirs = {
			"tables", "foreign_keys", "assemblies", "functions", "procedures", "triggers",
			"views", "xmlschemacollections", "data", "users", "synonyms"
		};

**Comment by ChrisMDaly** [comment]
I copies the table_types to the functions folder to give it a go and found the following:

some of the UDT.SQL Files have a named constraint which (from what i understand) is not supported in UDT's.   This is causing the load of the .sql file to fail with "Incorrect syntax near the keyword 'CONSTRAINT'."    Once the Constraint [xxx] is removed, the file loads successfully.

Thanks!

CREATE TYPE [dbo].[ActionPanels_BulkTypexx] AS TABLE (
   [ActionPanelID] [int] NOT NULL   ,
   [SiteID] [int] NOT NULL   ,
   [ActionID] [int] NULL   ,
   [PanelID] [int] NULL   ,
   [CreationDate] [datetime] NULL   ,
   [UpdateBySQLUser] [nvarchar](128) NULL ,
   [UpdateDateUTC] [datetime] NULL   ,
   [ToDelete] [bit] NULL   ,
   [UID] [uniqueidentifier] NULL   ,
   [sync_update_peer_timestamp] [bigint] NULL   ,
   [sync_update_peer_key] [int] NULL   ,
   [sync_create_peer_timestamp] [bigint] NULL   ,
   [sync_create_peer_key] [int] NULL   ,

   CONSTRAINT  PK__TT_Actio__CD95B63DEFAD247E PRIMARY KEY CLUSTERED ([ActionPanelID], [SiteID])
)

**Comment by keith-hall** [comment]
Hi, thanks for reporting :) I am working on a test case and fix :)

**Comment by keith-hall** [comment]
I have made a test case and a fix, but at the moment, I have had to skip the code that compares constraints on table types, because they have names in the DB but not in the script (SQL Server automatically assigns them names). This means that, without skipping the code, it would always fail an equality check. I am working on a way to determine if the constraints on table types are identical.

**Comment by sethreno** [comment]
Hey @ChrisMDaly, Will you download the latest release and verify this is fixed please?

**Comment by ChrisMDaly** [comment]
done and it looks good!    I did find another issue for you guys which i will document.

Again, thanks for your tool!
