### ISSUE TITLE
Option to DROP all destination database objects instead of the database itself [Feature Request]

### ISSUE THREAD

**Issue by jhelmink** [sethreno/schemazen#59]
A lot of Shared Hosting providers will not let you perform any actions on the 'master' database, so a CREATE DATABASE command will fail.

I have a SQL script that drops all objects within a database that could be used as an alternative to dropping the whole database itself before restoring it's contents. (Note I did not write this script)
[DropAllObjects.txt](https://github.com/sethreno/schemazen/files/99997/DropAllObjects.txt)

**Comment by keith-hall** [comment]
Maybe your use case would also be served by using the compare feature, once [comparing from a script directory](https://github.com/sethreno/schemazen/issues/26) is implemented?

**Comment by jhelmink** [comment]
Yes it looks like that would also work. I haven't used a Compare tool before, but so as long as the end result is a copy of the database matching the master that would be perfect.
