### ISSUE TITLE
SchemaZen doesn't script CHECK constraints

### ISSUE THREAD

**Issue by keith-hall** [sethreno/schemazen#60]
Given the following table,

    CREATE TABLE [dbo].[CheckTest] (
        [CheckTestValue] [varchar](25) NOT NULL 
              CHECK (CheckTestValue != '')
    )

SchemaZen scripts it as:

    CREATE TABLE [dbo].[CheckTest] (
       [CheckTestValue] [varchar](25) NOT NULL 
    )
    
    GO

[This](http://stackoverflow.com/a/2499396/4473405) shows that we can get check constraint information from SQL using:

    SELECT * FROM INFORMATION_SCHEMA.CHECK_CONSTRAINTS

but it lacks table information, but can be combined with:

    SELECT OBJECT_NAME(OBJECT_ID) AS ConstraintName
        ,SCHEMA_NAME(schema_id) AS SchemaName
        ,OBJECT_NAME(parent_object_id) AS TableName
    FROM sys.objects
    WHERE type_desc = 'CHECK_CONSTRAINT'

(which lacks the check definition).

**Comment by sethreno** [comment]
Hey Keith, when you get a chance please download the latest version and verify this issue is fixed. Thanks.
