### ISSUE TITLE
Getting errors for SQL Server 2016 CTP3

### ISSUE THREAD

**Issue by rangedsp** [sethreno/schemazen#65]
Heya,

I'm getting this error when running against SQL Server 2016 CTP3
![image](https://cloud.githubusercontent.com/assets/4970707/12865469/686e5eb4-cd11-11e5-9824-07339910d6db.png)

Would be nice if it's fixed eventually

Cheers,
Jonny

**Comment by sethreno** [comment]
Thanks for reporting, but this is a duplicate of #34

**Comment by sethreno** [comment]
This should be fixed. Please get the latest version and verify. Thanks!
