### ISSUE TITLE
Support of [nvarchar](max) type

### ISSUE THREAD

**Issue by Atrony** [sethreno/schemazen#66]
If you have such type
```
CREATE TYPE [dbo].[SessionData] AS TABLE(
	[OperatorName] [nvarchar](max) NULL
)
```

after scripting you receive
```
CREATE TYPE [dbo].[SessionData] AS TABLE(
	[OperatorName] [nvarchar](0) NULL
)
```

It can't be recreated later.

SQL Edition: Microsoft SQL Server 2008 (RTM) - 10.0.1600.22 (X64)

**Comment by sethreno** [comment]
This was fixed in a recent pull request. Please try out the latest release and verify it's fixed. Thanks!
