### ISSUE TITLE
Indexes with columns using DESC sort order

### ISSUE THREAD

**Issue by keith-hall** [sethreno/schemazen#72]
Given the following script:
```sql
CREATE NONCLUSTERED INDEX [IX_Test_1] ON [dbo].[Test]
(
	[TestID] DESC
)
```

SchemaZen currently does not honor the column sort order, and scripts it as:
```sql
CREATE  NONCLUSTERED INDEX [IX_Test_1] ON [dbo].[Test] ([TestID])
```

Column `sys.index_columns.is_descending_key` can be used to determine if a column in an index should be sorted in descending order.

**Comment by benjamin-hodgson** [comment]
This issue is affecting me too.
