### ISSUE TITLE
String Interpolation

### ISSUE THREAD

**Issue by chipx0r** [sethreno/schemazen#93]
File: model.Constraint.cs
Line: 44
return $"CONSTRAINT [{Name}] CHECK {notForReplicationOption} {CheckConstraintExpression}";
Sting Interpolation is feature that is not supported in VS2013, Only in VS2015

To mantain compatibility with older compilers, please replace with:
return string.Format("CONSTRAINT [{0}] CHECK {1} {2}", Name, notForReplicationOption, CheckConstraintExpression);

**Comment by sethreno** [comment]
I plan to eventually replace all the string formatting with string interpolation. It's much more readable.
