### ISSUE TITLE
How to exclude tables from script

### ISSUE THREAD

**Issue by WinmanSoftwarePvtLtd** [sethreno/schemazen#94]
Hello,
Suppose if I dont want table details in the script, then how can I exclude tables from the scripting ?
Please help.

**Comment by kdd21** [comment]
I needed this capability as well, but couldn't find a straightforward way to do it.   One saving grace of the program is the export is written to a folder where each database object is a separate file.   What we ended up doing is wrappering it with a script that after the export, deletes a list of files we don't want out of the tables folder (<tablename>.sql).    Worked fine.   Also did this with views, foreign keys and stored procs.   Not pretty, but it worked.

**Comment by WinmanSoftwarePvtLtd** [comment]
Thank you. I knew it. But that is not a possible case to me. I am working on hundreds of database.

**Comment by sethreno** [comment]
Support for ignoring tables was added in version 1.3.40 via the filterTypes command line option.

This was fixed in commit 39d719ad6c1e49bcef0c94631c0de67669c30d11
