### ISSUE TITLE
Problem with numeric columns and identity specification

### ISSUE THREAD

**Issue by keithn** [sethreno/schemazen#96]
had to change column.cs to

`case "numeric":

						return string.Format("[{0}] [{1}]({2},{3}) {4} {5} {6}", Name, Type, Precision, Scale, IsNullableText,
							includeDefaultConstraint ? DefaultText : string.Empty,  IdentityText);`

**Comment by sethreno** [comment]
Thanks for reporting. This will be fixed in the next release.
